name: Trigger auto deployment for container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-AutoDeployTrigger-0c428cad-6569-4b83-8d70-21ede645218e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.CONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: neos79/neo-spring-app:master${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app -g neo-rg --server docker.io --username  ${{ secrets.CONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n container-app -g neo-rg --image neos79/neo-spring-app:${{ github.sha }}
