name: Trigger auto deployment for neo-container-spring-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/neo-container-spring-app-AutoDeployTrigger-03af30ac-7bf4-4aff-a165-b83d3e6fc630.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: neospring.azurecr.io
          username: ${{ secrets.NEOCONTAINERSPRINGAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.NEOCONTAINERSPRINGAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: neospring.azurecr.io/neo-container-spring-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEOCONTAINERSPRINGAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n neo-container-spring-app -g neo-rg-ca --server neospring.azurecr.io --username  ${{ secrets.NEOCONTAINERSPRINGAPP_REGISTRY_USERNAME }} --password ${{ secrets.NEOCONTAINERSPRINGAPP_REGISTRY_PASSWORD }}
            az containerapp update -n neo-container-spring-app -g neo-rg-ca --image neospring.azurecr.io/neo-container-spring-app:${{ github.sha }}
